subscriptionIds:
  - "00000000-0000-0000-0000-000000000000"

ignoreResourceIDPatterns: []

ignoreResourceTypePatterns: []

resourceGraphQueries:
  - name: "Resource Groups"
    scope: "Subscription"
    query: |
      resources
      | where type == "microsoft.resources/resourcegroups"
      | project id, name, type, location, subscriptionId, resourceGroup

nameFormats: []

deleteCommands: []
